name: 'Upload_3000'
description: 'Upload codeql database to Codeql Central'
inputs:
  user_mame:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: '../lib/action-upload.js'